import {images} from '../images'

export default [
    {
        id: 1,
        name: "Johnny Depp",
        desc: "John Christopher Depp II (born June 9, 1963) is an American actor, producer, and musician. He is the recipient of multiple accolades, including a Golden Globe Award and a Screen Actors Guild Award, in addition to nominations for three Academy Awards and two BAFTA awards.",
        amount: "15000",
        amount1: "10000",
        img1: `${images.jo1}`,
        img2: `${images.jo2}`,
        img3: `${images.jo3}`,
        img4: `${images.jo4}`,
        img5: `${images.jo5}`,
        bio1: "John Christopher Depp II was born on June 9, 1963, in Owensboro, Kentucky, the youngest of four children of waitress Betty Sue Palmer (née Wells) and civil engineer John Christopher Depp. Depp's family moved frequently during his childhood, eventually settling in Miramar, Florida, in 1970. His parents divorced in 1978 when he was 15, and his mother later married Robert Palmer, whom Depp has called 'an inspiration'",
        bio2: "Depp's mother gave him a guitar when he was 12, and he began playing in various bands. He dropped out of Miramar High School at 16 in 1979 to become a rock musician. He attempted to go back to school two weeks later, but the principal told him to follow his dream of being a musician. In 1980, Depp began playing in a band called The Kids. After modest local success in Florida, the band moved to Los Angeles in pursuit of a record deal, changing its name to Six Gun Method. In addition to the band, Depp worked a variety of odd jobs, such as in telemarketing. In December 1983, Depp married makeup artist Lori Anne Allison, the sister of his band's bassist and singer. The Kids split up before signing a record deal in 1984, and Depp began collaborating with the band Rock City Angels.[16] He co-wrote their song 'Mary', which appeared on their debut Geffen Records album Young Man's Blues. Depp and Allison divorced in 1985.",
        fa: 'https://www.facebook.com/JohnnyDepp',
        tw: 'https://twitter.com/JohnnyDeppNFT',
        ig: 'https://www.instagram.com/johnnydepp/?hl=en',
    },
    {
        id: 2,
        name: "Jason Momoa",
        desc: "Joseph Jason Namakaeha Momoa (born August 1, 1979) is an American actor. He made his acting debut as Jason Loane on the syndicated action drama series Baywatch: Hawaii (1999–2001), which was followed by portrayals of Ronon Dex on the Syfy science fiction series Stargate Atlantis (2005–2009),",
        amount: "13000",
        amount1: "9000",
        img1: `${images.ja1}`,
        img2: `${images.ja2}`,
        img3: `${images.ja3}`,
        img4: `${images.ja4}`,
        img5: `${images.ja5}`,
        bio1: "An only child, Momoa was born on August 1, 1979, in Honolulu, Hawaii, to Coni (Lemke), a photographer, and Joseph Momoa, a painter. He moved with his mother to Norwalk, Iowa, at the age of six months, and lived there until he graduated from high school and returned to Honolulu to attend the University of Hawaii. His father is of Native Hawaiian ancestry and his mother is of German and Irish heritage, with self-identified Pawnee ancestry.",
        bio2: "At 19 years old, while living and working in Honolulu, Momoa decided to audition for the television series Baywatch Hawaii, in which he was cast as Jason Ioane (1999–2001)",
        fa: 'https://www.facebook.com/1JasonMomoaFans',
        tw: 'https://twitter.com/jasonmomoa_th?lang=en',
        ig: 'https://www.instagram.com/prideofgypsies/',
    },
    {
        id: 3,
        name: "Henry Cavill",
        desc: "Henry William Dalgliesh Cavill (/ˈkævəl/; born 5 May 1983) is a British actor. He is known for his portrayal of Charles Brandon in Showtime's The Tudors (2007–2010), DC Comics character Superman in the DC Extended Universe, Geralt of Rivia in the Netflix fantasy series The Witcher (2019–present)",
        amount: "12500",
        amount1: "7000",
        img1: `${images.ca1}`,
        img2: `${images.ca2}`,
        img3: `${images.ca3}`,
        img4: `${images.ca4}`,
        img5: `${images.ca5}`,
        bio1: "Cavill was born on 5 May 1983, the fourth of five boys in a Roman Catholic family at Saint Helier, Jersey, in the Channel Islands. His mother, Marianne Dalgliesh, was a secretary in a bank. She was born in Jersey and is of Scottish, English and Irish heritage. His father, Colin Cavill, was born in Chester, England and was a stockbroker. He was educated at St Michael's Preparatory School in Saint Saviour, Jersey, before attending Stowe School in Stowe, Buckinghamshire. In 2000, while playing rugby, 16-year-old Cavill met actor Russell Crowe, who was shooting on location at Stowe for the film Proof of Life. The actor shared some acting tips and later sent a package to his boarding school. The two actors later worked together on Man of Steel.",
        bio2: "Cavill began his film career with a role in Laguna (2001) and Kevin Reynolds' adaptation of The Count of Monte Cristo (2002). He continued with appearances in BBC's The Inspector Lynley Mysteries (2002), the television film Goodbye, Mr. Chips (2002), and the television series Midsomer Murders (2003). In 2003, he had a supporting role in I Capture the Castle, followed by Hellraiser: Hellworld (2005), Red Riding Hood (2006) and Tristan & Isolde (2006). He had a minor role in Matthew Vaughn's adaptation of Stardust (2007).",
        fa: 'https://www.facebook.com/henrycavill',
        tw: '#',
        ig: 'https://www.instagram.com/henrycavill/?hl=en',
    },
    {
       
        id: 4,
        name: "Ian Somerhalder",
        desc: "Ian Joseph Somerhalder (born December 8, 1978) is an American actor, model, and activist. He is known for playing Boone Carlyle in the TV drama Lost, Damon Salvatore in The CW's supernatural drama The Vampire Diaries and Dr. Luther Swann in Netflix's sci-fi horror series V Wars.",
        amount: "10500",
        amount1: "6000",
        img1: `${images.ia1}`,
        img2: `${images.ia2}`,
        img3: `${images.ia3}`,
        img4: `${images.ia4}`,
        img5: `${images.ia5}`,
        bio1: "Somerhalder was born and raised in Covington, Louisiana, the son of Edna, a massage therapist, and Robert Somerhalder, an independent building contractor. He is the second of three children, with an older brother, Robert, and younger sister, Robyn. He attended Saint Paul's School, a private school in Covington. He embarked on a modeling career from age 10 to 13, and by the age of 17 he decided to go into acting.",
        bio2: "In the summer of 2000, Somerhalder starred in the short-lived WB series Young Americans, a spin-off of Dawson's Creek. He played Hamilton Fleming, the son of the dean of a prestigious boarding school. In 2002, Somerhalder played bisexual character Paul Denton in Roger Avary's adaptation of Bret Easton Ellis' novel, The Rules of Attraction, alongside James Van Der Beek, Shannyn Sossamon, and Jessica Biel.",
        fa: 'https://www.facebook.com/iansomerhalderofficial',
        tw: 'https://twitter.com/iansomerhalder?lang=en',
        ig: 'https://www.instagram.com/iansomerhalder/?hl=en',
    },
    {
        id: 5,
        name: "Luke Bryan",
        desc: "Thomas Luther 'Luke' Bryan (born July 17, 1976) is an American country singer and songwriter. He began his music career writing songs for Travis Tritt and Billy Currington before signing with Capitol Nashville in 2007. He is one of the most successful and awarded country artists of the 2010s and 2020s.",
        amount: "11500",
        amount1: "7000",
        img1: `${images.br1}`,
        img2: `${images.br2}`,
        img3: `${images.br3}`,
        img4: `${images.br4}`,
        img5: `${images.br5}`,
        bio1: "Luke Bryan was born in Leesburg, Georgia, to LeClaire and Tommy Bryan, a peanut farmer. Shortly before Luke was going to move to Nashville at age 19, his elder brother Chris was unexpectedly killed in a ... car accident ... I'm kind of hyperventilating talking about it. ... You never truly ... move beyond it.  His mother, LeClaire, had made a statement: 'We knew Luke at some point would come to Nashville,' his mother said. 'But ... you can't leave your family, and ... I couldn/'t bear the thought of him being away.",
        bio2: "Instead, Luke went to college at Georgia Southern University in Statesboro, Georgia, where he joined the Sigma Chi fraternity and graduated in 1999 with a bachelor's degree in business administration. Two years later, Bryan finally made it to Nashville, after his father told him to pack his truck to pursue a career in music. He initially gained success as a songwriter, but soon after signed as a performer; his first major success was 'All My Friends Say'.",
        fa: 'https://www.facebook.com/lukebryan',
        tw: 'https://twitter.com/lukebryan?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        ig: 'https://www.instagram.com/lukebryan/?hl=en',
    },
    {
       
        id: 6,
        name: "Jensen Ackles",
        desc: "Jensen Ross Ackles (born March 1, 1978) is an American actor. He is best known for his portrayal of Dean Winchester in The WB/CW dark fantasy drama series Supernatural (2005-2020) and appearing in television series such as NBC’s Days of Our Lives as Eric Brady (earning him several Daytime Emmy Award nominations).",
        amount: "13500",
        amount1: "8000",
        img1: `${images.je1}`,
        img2: `${images.je2}`,
        img3: `${images.je3}`,
        img4: `${images.je4}`,
        img5: `${images.je5}`,
        bio1: "Ackles was born in Dallas the son of Donna Joan (née Shaffer) and Alan Roger Ackles, an actor. He grew up in Richardson and attended Lloyd V. Berkner High School. After graduating in 1996, he moved to Los Angeles to begin his acting career.",
        bio2: "After modeling on and off since the age of four, Ackles began to concentrate on an acting career in 1996. He appeared in several guest roles on Mr. Rhodes, Sweet Valley High, and Cybill before joining the cast of the NBC soap opera Days of Our Lives as Eric Brady in 1997. He won a 1998 Soap Opera Digest Award for Best Male Newcomer and went on to be nominated three times (in 1998, 1999, and 2000) for a Daytime Emmy Award for Outstanding Younger Actor in a Drama Series for his work on Days of our Lives.",
        fa: 'https://www.facebook.com/JensenAckles',
        tw: 'https://twitter.com/jensenackles',
        ig: 'https://www.instagram.com/jensenackles/?hl=en',
    },
    {
        id: 7,
        name: "Kit Harrington",
        desc: "Christopher Catesby Harington (born 26 December 1986) is an English actor. He studied at the Royal Central School of Speech and Drama and made his professional acting debut with the lead role of Albert Narracott in the West End play War Horse in 2009. In 2011, his breakthrough role as Jon Snow in the HBO epic fantasy television series Game of Thrones",
        amount: "13500",
        amount1: "7500",
        img1: `${images.ki1}`,
        img2: `${images.ki2}`,
        img3: `${images.ki3}`,
        img4: `${images.ki4}`,
        img5: `${images.ki5}`,
        bio1: "Christopher Catesby Harington was born on 26 December 1986 in Acton, London. His mother named him after Christopher Marlowe, whose first name was shortened to Kit, a name Harington prefers. He did not learn what his full name was until he was eleven years old. His parents are Sir David Harington, 15th Baronet, a businessman, and former playwright Deborah Jane, daughter of Maurice William ('Mick') Catesby (1915-1994), MC, of Long Compton, Warwickshire, who was managing director of Gamages department store in London after first working for the family business, Catesby's, a furnishing department store on Tottenham Court Road; he had been an officer in the Royal Artillery, including at the Battle of Monte Cassino. Through his father, Harington descends from Scottish politician Henry Dundas, 1st Viscount Melville. Harington is related to men who were involved on opposite sides of the Gunpowder Plot. He claims a family connection with the leader of the plot, Robert Catesby, on his mother's side, while through his father's side, he is related to King James I (grandfather of King Charles II), the target of the assassination attempt, and to Lord Harington, who was in the Houses of Parliament that Catesby and his co-conspirators tried to blow up.",
        bio2: "Harington was a pupil at the Southfield Primary School from 1992 to 1998. When he was 11, his family moved to Worcestershire and he studied at the Chantry High School in Martley until 2003. He became interested in acting after watching a production of Waiting for Godot when he was 14, and he performed in several school productions. He attended Worcester Sixth Form College, where he studied Drama and Theatre (2003–05). When he was 17, he was inspired to attend a drama school after seeing a performance by Ben Whishaw as Hamlet in 2004. Harington moved back to London in 2005 when he was eighteen after completing Sixth Form and, later that year, attended the Central School of Speech and Drama, graduating in 2008.",
        fa: 'https://www.facebook.com/JensenAckles',
        tw: 'https://twitter.com/jensenackles',
        ig: 'https://www.instagram.com/jensenackles/?hl=en',
    },
    {
        id: 8,
        name: "Patrick Dempsey",
        desc: "Patrick Galen Dempsey (born January 13, 1966) is an American actor and race car driver, best known for his role as neurosurgeon Derek 'McDreamy' Shepherd in Grey's Anatomy. He had early success as an actor, starring in a number of films in the 1980s, including Can't Buy Me Love (1987) and Loverboy (1989). In the 1990s, he mostly appeared in smaller roles in film.",
        amount: "12500",
        amount1: "8500",
        img1: `${images.de1}`,
        img2: `${images.de2}`,
        img3: `${images.de3}`,
        img4: `${images.de4}`,
        img5: `${images.de5}`,
        bio1: "Dempsey was born in Lewiston, Maine, and grew up in the nearby towns of Turner and Buckfield. He has two older sisters and a half-brother, Shane Wray. His mother, Amanda (née Casson), was a school secretary, and his father, William, was an insurance salesman.",
        bio2: "An invitation to audition for a role in the stage production of Torch Song Trilogy led to Patrick Dempsey's discovery as an actor. His audition was successful and he spent the following four months touring with the company in Philadelphia. He followed this with another tour, Brighton Beach Memoirs, in the lead role, which was directed by Gene Saks. Dempsey has also made notable appearances in the stage productions of On Golden Pond, with the Maine Acting Company, and as Timmy (the Martin Sheen role) in a 1990 off-Broadway revival of The Subject Was Roses co-starring with John Mahoney and Dana Ivey at the Roundabout Theatre in New York.",
        fa: 'https://www.facebook.com/patrickdempseyofficial',
        tw: 'https://twitter.com/patrickdempsey',
        ig: 'https://www.instagram.com/patrickdempsey/?hl=en',
    },
    {
        id: 9,
        name: "Denzel Washington",
        desc: "Denzel Hayes Washington Jr. (born December 28, 1954) is an American actor, director, and producer. Known for his performances on the screen and stage, he has been described as an actor who reconfigured 'the concept of classic movie stardom'. He is also known for his frequent collaborations with directors Spike Lee, Antoine Fuqua, and Tony Scott.",
        amount: "14000",
        amount1: "9500",
        img1: `${images.wa1}`,
        img2: `${images.wa2}`,
        img3: `${images.wa3}`,
        img4: `${images.wa4}`,
        img5: `${images.wa5}`,
        bio1: "Denzel Hayes Washington Jr. was born in Mount Vernon, New York, on December 28, 1954. His mother, Lennis 'Lynne', was a beauty parlor owner and operator born in Georgia and partly raised in Harlem, New York. His father, Denzel Hayes Washington Sr., a native of Buckingham County, Virginia, was an ordained Pentecostal minister, who was also an employee of the New York City Water Department, and worked at a local S. Klein department store.",
        bio2: "Washington attended Pennington-Grimes Elementary School in Mount Vernon until 1968. When he was 14, his parents divorced and his mother sent him to the private preparatory school Oakland Military Academy in New Windsor, New York. Washington later said, 'That decision changed my life, because I wouldn't have survived in the direction I was going. The guys I was hanging out with at the time, my running buddies, have now done maybe 40 years combined in the penitentiary. They were nice guys, but the streets got them.' After Oakland, he attended Mainland High School in Daytona Beach, Florida, from 1970 to 1971. He was interested in attending Texas Tech University: 'I grew up in the Boys Club in Mount Vernon, and we were the Red Raiders. So when I was in high school, I wanted to go to Texas Tech in Lubbock just because they were called the Red Raiders and their uniforms looked like ours.' Instead, he earned a BA in Drama and Journalism from Fordham University in 1977. At Fordham, he played collegiate basketball as a guard under coach P.J. Carlesimo. After a period of indecision on which major to study and taking a semester off, Washington worked as creative arts director of the overnight summer camp at Camp Sloane YMCA in Lakeville, Connecticut. He participated in a staff talent show for the campers and a colleague suggested he try acting",
        fa: 'https://www.facebook.com/Denzel-Washington-Actor-1655621238031573/',
        tw: 'https://twitter.com/officiaidenzei?lang=en',
        ig: 'https://www.instagram.com/denzelwashington.official/?hl=en',
    },
    {
        id: 10,
        name: "Chris Evans",
        desc: "Christopher Robert Evans (born June 13, 1981) is an American actor. He began his career with roles in television series, such as in Opposite Sex in 2000. Following appearances in several teen films including 2001's Not Another Teen Movie, he gained attention for his portrayal of Marvel Comics character the Human Torch in Fantastic Four (2005) and Fantastic Four",
        amount: "13000",
        amount1: "8500",
        img1: `${images.ch1}`,
        img2: `${images.ch2}`,
        img3: `${images.ch3}`,
        img4: `${images.ch4}`,
        img5: `${images.ch5}`,
        bio1: "Christopher Robert Evans was born on June 13, 1981, in Boston, Massachusetts, and grew up in the nearby town of Sudbury. His mother, Lisa (née Capuano), is an artistic director at the Concord Youth Theater, and his father, Bob, is a dentist. His parents divorced in 1999.",
        bio2: "Evans has two sisters, Carly and Shanna, and a brother, actor Scott Evans. He and his siblings were raised Catholic. Their uncle, Mike Capuano, represented Massachusetts's 8th congressional district. Evans has Irish, and from his maternal grandfather, Italian, ancestry.",
        fa: 'https://www.facebook.com/search/top/?q=Chris+Evans',
        tw: 'https://twitter.com/ChrisEvans?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        ig: 'https://www.instagram.com/chrisevans/?hl=en',
    },
    {
        id: 11,
        name: "Brad Pitt",
        desc: "William Bradley Pitt (born December 18, 1963) is an American actor and film producer. He is the recipient of various accolades, including an Academy Award, a British Academy Film Award, two Golden Globe Awards, two Screen Actors Guild Award and a Primetime Emmy Award. In 2001, Pitt co-founded the production company, Plan B Entertainment which has produced various films",
        amount: "13000",
        amount1: "9500",
        img1: `${images.pi1}`,
        img2: `${images.pi2}`,
        img3: `${images.pi3}`,
        img4: `${images.pi4}`,
        img5: `${images.pi5}`,
        bio1: "William Bradley Pitt was born on December 18, 1963, in Shawnee, Oklahoma, to William Alvin Pitt, the proprietor of a trucking company, and Jane Etta (née Hillhouse), a school counselor. The family soon moved to Springfield, Missouri, where he lived together with his younger siblings, Douglas Mitchell (born 1966) and Julie Neal (born 1969). Born into a conservative Christian household, he was raised as Southern Baptist and later 'oscillate between agnosticism and atheism.' He later reconciled his belief in spirituality. Pitt has described Springfield as 'Mark Twain country, Jesse James country,' having grown up with 'a lot of hills, a lot of lakes.'",
        bio2: "Pitt is very distantly related to the 44th president of the United States, Barack Obama. The two have a common ancestor from the 18th century named Edwin Hickman.",
        fa: 'https://www.facebook.com/profile.php?id=100044628330280',
        tw: '#',
        ig: 'https://www.instagram.com/bradpittofflcial/?hl=en',
    },
    {
        id: 12,
        name: "Bradley Cooper",
        desc: "Bradley Charles Cooper (born January 5, 1975) is an American actor and filmmaker. He is the recipient of various accolades, including a British Academy Film Award and two Grammy Awards, in addition to nominations for nine Academy Awards, six Golden Globe Awards, and a Tony Award. Cooper appeared on the Forbes Celebrity 100 three times and on Time's list of the 100 most influential people in the world in 2015.",
        amount: "13500",
        amount1: "8500",
        img1: `${images.co1}`,
        img2: `${images.co2}`,
        img3: `${images.co3}`,
        img4: `${images.co4}`,
        img5: `${images.co5}`,
        bio1: "Cooper was born on January 5, 1975, in Abington Township, near Philadelphia, and grew up in the nearby communities of Jenkintown and Rydal. His mother, Gloria (née Campano), worked for the local NBC affiliate. His father, Charles Cooper, worked as a stockbroker for Merrill Lynch. Cooper's father was of Irish descent, while his mother is of Italian ancestry (from Abruzzo and Naples). He has an older sister, Holly. He had cholesteatoma in his ear soon after his birth, and punctured his eardrum when he started diving at an early age.",
        bio2: "Describing himself as a child, Cooper has said: 'I never lived the life of 'Oh, you're so good-looking'. People thought I was a girl when I was little, because I looked like a girl—maybe because my mother would keep my hair really long'. He excelled at basketball, and enjoyed cooking: 'I used to have buddies come over after kindergarten and I did cook them food. I prided myself in taking whatever was in the fridge and turning it into lasagna.' He initially wanted to attend Valley Forge Military Academy and move to Japan to become a ninja. At an early age, his father introduced him to films like The Elephant Man, which inspired him to be an actor. Coming from a family of non-actors, Cooper says that his parents initially wanted him to pursue a career in finance and was against acting, but they eventually changed their perceptions when they saw Cooper play the part of Joseph Merrick in an excerpt from the play The Elephant Man.",
        fa: '#',
        tw: '#',
        ig: 'https://www.instagram.com/bradleycooper__original/?hl=en',
    },
    
    {
        id: 13,
        name: "Thomas Mark Harmon",
        desc: "Thomas Mark Harmon (born September 2, 1951) is an American actor. He is most famous for playing the lead role of Leroy Jethro Gibbs in NCIS. He also has appeared in a wide variety of roles since the early 1970s. Initially a college football player, he was named 'Sexiest Man Alive' by People magazine in 1986, due largely to his role as Dr. Robert Caldwell on St. Elsewhere, a role notable for being one of the first TV characters that had HIV.",
        amount: "12500",
        amount1: "7500",
        img1: `${images.th1}`,
        img2: `${images.th2}`,
        img3: `${images.th3}`,
        img4: `${images.th4}`,
        img5: `${images.th5}`,
        bio1: "Harmon was born in Burbank, California, the youngest of three children. His parents were Heisman Trophy–winning football player and broadcaster Tom Harmon and actress, model, and artist Elyse Knox (née Elsie Lillian Kornbrath). Harmon had two older sisters, the late actress and painter Kristin Nelson, who was divorced from the late singer Rick Nelson, and actress and model Kelly Harmon, formerly married to car magnate John DeLorean. His maternal grandparents were Austrian immigrants.",
        bio2: "He was inducted into the inaugural class of the Pierce College Athletic Hall of Fame in 2010.",
        fa: '#',
        tw: '#',
        ig: '#',
    },
  
];
